### ISSUE TITLE
Smelting, Blasting, Smoking and Campfire cooking not working in 1.15.2

### ISSUE THREAD

**Issue by John147GHN** [Goldorion/MCreatorFabricGenerator#5] opened 2020-06-05 19:22 UTC
As the title says, it's not possible to create Smelting, Blasting and Smoking recipes as of 1.15.2. You can "create them" but the recipes won't even appear in the actual game.
I checked and I can do these recipes using forge. I made a simple "smelting a chest gives a diamond" recipe and it doesn't work in my mod's workplace nor creating a new workplace with this single recipe. Any help is greatly appreciated.

**Comment by Goldorion** [comment] 2020-06-06 02:20
I know the cause, but I don't know how to fix it. I need to rewrite a section of th mcitems.ftl file (used to write the right code when we selecte an item, a block or a modded thing). I'm still trying to change the code, and then many things will work (and I will be able to release a new dev version).

**Comment by Goldorion** [comment] 2020-06-10 21:49
I found the cause. It will be fixed in the next update.

**Closed as completed by Goldorion** 2020-06-10 21:49 UTC
Labels: bug
