### ISSUE TITLE
Your workplace contains mod elements that don't compile and could not be exported no mod file was generated.

### ISSUE THREAD

**Issue by PlainDust** [Goldorion/MCreatorFabricGenerator#40] opened 2020-07-01 15:45 UTC
The bug happens when exporting.

The Versions
 Fabric Generator [Plugin] - 0.6.1 - 1.15.2
 MCreator -  2020.3

Here is a image of the [ERROR](https://i.imgur.com/aLF7rmW.png)

is strange because i can go to the Build&Run tab and run client the mod works but as soon as i try to export it i get that error.
i also went to the lib folder and got the "modid-1.0.jar" and put it on minecraft and it worked.
   Here is the File
[TTProject.zip](https://github.com/ClothCreators/MCreatorFabricGenerator/files/4858883/TTProject.zip)

**Comment by Goldorion** [comment] 2020-07-01 15:48
I can confirm the bug, but we are not 100% sure why it happens.

**Comment by PlainDust** [comment] 2020-07-01 15:52
Is strange i deleted the gradle folder thinking it was that, i deleted the project and restarted, i check and there is no wrong mod elements. The problem is with the export.

**Comment by Goldorion** [comment] 2020-07-01 15:54
Yeah, I know. it's something inside the generator.yaml I did wrong.

**Comment by PlainDust** [comment] 2020-07-01 15:55
Sorry! I posted the error here https://mcreator.net/forum/60201/fabric-generator-plugin?page=6%2C0 but they told me to post the issue here

**Comment by Goldorion** [comment] 2020-07-01 16:00
I think I found the cause. I asked to the generator to use a file that didn't exist in the generator.yaml. I'm testing this fix, and I will tell you if it works.

**Comment by Goldorion** [comment] 2020-07-01 16:04
It was the cause. I'm closing the issue.

**Closed as completed by Goldorion** 2020-07-01 16:04 UTC
Labels: bug

**Comment by LaMelancholie** [comment] 2022-11-30 04:55
> I think I found the cause. I asked to the generator to use a file that didn't exist in the generator.yaml. I'm testing this fix, and I will tell you if it works.

How did you fix this?

**Comment by PlainDust** [comment] 2022-11-30 13:08
Oh thats great

On Tuesday, November 29, 2022, LaMelancholie ***@***.***>
wrote:
> I think I found the cause. I asked to the generator to use a file that
didn't exist in the generator.yaml. I'm testing this fix, and I will tell
you if it works.
>
> How did you fix this?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/p8PlxMNuOYFOx0RVxJ1Bp84aghXd7YVlXPB8FmHVZ9_eCJ0PhifjpRuC120lZOMLTyQV04Cpt0htL1RN28WRkzUaP-ghBICe4MQHlIJ3wkRLqu_IEF7-BApL1gDyYZfIjRrpTwbInpdHZs-wqWCiPgBFSRZg5f5fSRptMlYi6V2ebSnowPQmAZlejvnI2froj69rV-Bi-hWZpgwBkI7Wkk8ND3I7JFs50XLTmwzLXw=s0-d-e1-ft#https://github.com/notifications/beacon/AP6UWUECVSGIXQQLVMRSTKTWK3M3VA5CNFSM4ONRKCMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOJ5PUBYI.gif>Message
ID: ***@***.***>
