### ISSUE TITLE
[Bug] Can't build in latest snapshot 2021.2 EAP (26215)

### ISSUE THREAD

**Issue by ultimateimmersion** [Goldorion/MCreatorFabricGenerator#127] opened 2021-07-07 08:04 UTC
I've tried deleting the gradle folder and made a build on previously working project but I'm still getting a ton of errors on the most simple blockIDs using only a JSON model, name and bounding box change from default).

Log:
[https://pastebin.com/ZuEQw0Q3](https://pastebin.com/ZuEQw0Q3)

How did you make it run on my previously sent workspace with this? I've tried every single option in build dropdown and none made my workspace compile without errors in the end.

**Comment by Goldorion** [comment] 2021-07-28 05:13
I will close this issue for the moment because 2021.2 make several major changes in the code, so this is not a bug. The plugin needs to be updated to support new changes and features. I'm working on a small update and I added the option to disable the plugin when MCreator 2021.1 is not used.

**Closed as completed by Goldorion** 2021-07-28 05:13 UTC

**Comment by ultimateimmersion** [comment] 2021-07-28 09:42
Ok, I did try the latest MCreator EAP 2021.2 b31709 snapshot few days ago and it did compile everything but the creative tabs. After I deleted creative tabs it would compile and export. Those were working in the previous Fabric plugin versions so it's only that that's missing at least from my side.
