### ISSUE TITLE
Having issues compiling any procedure

### ISSUE THREAD

**Issue by xameryn** [Goldorion/MCreatorFabricGenerator#475] opened 2023-10-23 01:11 UTC
### Issue description

When giving a procedure a trigger (from the supported trigger list) the build always fails.

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/11352382/abc4841e-9c8c-4544-b708-21454380a4fe)
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/11352382/b6d861f3-c94c-463d-8ffc-1de1f84f40c9)

Bug occurs with every workspace and does not occur with forge generator (even when switching within the same workspace).

### How to reproduce this issue?

- Create a procedure
- Give it a trigger
- Click 'Save mod element'

### Operating system

Windows

### Details

MCreator: 2023.3
Generator: 1.20.1-1.9.9, older versions have the same issue as well.

### Logs

https://gist.github.com/xameryn/181fff195989b011bdb85bdfc3ed2d45

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment] 2023-10-27 18:51
Duplicate of #465

**Closed as not planned by Goldorion** 2023-10-27 18:51 UTC
Labels: bug, invalid
