### ISSUE TITLE
When making a trapdoor block, the mod element wont compile properly.

### ISSUE THREAD

**Issue by Night4-dev** [Goldorion/MCreatorFabricGenerator#444] opened 2023-08-05 10:59 UTC
### Issue description

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/111013596/b7ae2597-ce51-496b-83b4-a11231b02ab2)
when trying to make a trapdoor, this error pops up when trying to compile.
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/111013596/1ebe5190-4d23-451d-9c42-0c516c12e542)
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/111013596/886bf9eb-43a0-4067-878e-aaadebb5cea9)

### How to reproduce this issue?

Make a new Workspace with 1.20.1 fabric.
Make a Trapdoor.
Compile

### Operating system

Windows

### Details

Generator Type Fabric 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment] 2023-08-09 23:33
Duplicate of https://github.com/Goldorion/Fabric-Generator-MCreator/issues/444

**Closed as completed by Goldorion** 2023-08-09 23:33 UTC
Labels: bug, duplicate
